apiVersion: v1
kind: DeploymentConfig
metadata:
  name: mask-detection
  labels:
    app: mask-detection
spec:
  replicas: 1
  selector:
    name: mask-detection
    app: mask-detection
    servicetype: backend
    version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        name: mask-detection
        app: mask-detection
        servicetype: backend
        version: v1
      
    spec:
      containers:
        - name: mask-detection
          image: quay.io/ramesh_poomalai_in/mask-detection
          imagePullPolicy: Always
          readinessProbe: 
            tcpSocket:
              port: 8190
            initialDelaySeconds: 90  
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8190
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 512Mi                
---
# apiVersion: autoscaling/v2beta2 
# kind: HorizontalPodAutoscaler
# metadata:
#   name: mask-detection-autoscale
#   labels:
#     app: mask-detection
# spec:
#   scaleTargetRef:
#     apiVersion: v1 
#     kind: DeploymentConfig 
#     name: mask-detection
#   minReplicas: 1 
#   maxReplicas: 2 
#   metrics: 
#   - type: Resource
#     resource:
#       name: cpu 
#       target:
#         type: AverageValue 
#         averageValue: 6m       
#   # - type: Resource
  #   resource:
  #     name: memory 
  #     target:
  #       type: AverageValue 
  #       averageValue: 200Mi   
---
apiVersion: v1
kind: Service
metadata:
  name: mask-detection
  labels:
    app: mask-detection
spec:
  type: ClusterIP
  ports:
  - port: 8190
    name: http-8190
  selector:
    app: mask-detection              
---

